### ISSUE TITLE
Update to ESLint 4

### ISSUE THREAD

**Issue by grappler** [inpsyde/javascript#1]
Do you have any plans to update to ESLint 4.0?

http://eslint.org/docs/user-guide/migrating-to-4.0.0

**Comment by tfrommen** [comment]
Yes, absolutely.
Will have a look today or tomorrow.

(So, are you using our ESLint config then? Nice. 😀)

**Comment by grappler** [comment]
@tfrommen Great! I have not started using it as I have ESLint 4 installed but love to test it. I have been running ESLint on `_s`.

**Comment by tfrommen** [comment]
Done in https://github.com/inpsyde/javascript/commit/d0b6937c4496d5844d2f15692bdf39950ef56ef3.

Happy lintling. :)
